// Domain constants for the B-School Course Bidding Platform

export const USER_ROLES = {
  ADMIN: "ADMIN",
  PROFESSOR: "PROFESSOR",
  STUDENT: "STUDENT",
} as const;

export const PROGRAMME = {
  BM: "BM",
  HRM: "HRM",
  BOTH: "BOTH",
} as const;

export const BIDDING_ROUND_STATUS = {
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  CONFIRMED: "CONFIRMED",
} as const;

export const COURSE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  BIDDING_OPEN: "BIDDING_OPEN",
  BIDDING_CLOSED: "BIDDING_CLOSED",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
} as const;

export const ALLOCATION_STATUS = {
  TENTATIVE: "TENTATIVE",
  CONFIRMED: "CONFIRMED",
  WITHDRAWN: "WITHDRAWN",
  WAITLISTED: "WAITLISTED",
} as const;

export const TIE_BREAK_METHOD = {
  CQPI_DESC: "CQPI_DESC",
  GRADE_DESC: "GRADE_DESC",
  COMPOSITE_RANK: "COMPOSITE_RANK",
  LOTTERY: "LOTTERY",
  MANUAL_RANK: "MANUAL_RANK",
  SOP_SCORE: "SOP_SCORE",
} as const;

export const BID_STATUS = {
  ACTIVE: "ACTIVE",
  WINNING: "WINNING",
  LOSING: "LOSING",
  REIMBURSED: "REIMBURSED",
  WITHDRAWN: "WITHDRAWN",
} as const;

export const AUDIT_ACTION = {
  BID_PLACED: "BID_PLACED",
  BID_UPDATED: "BID_UPDATED",
  BID_WITHDRAWN: "BID_WITHDRAWN",
  ALLOCATION_CREATED: "ALLOCATION_CREATED",
  ALLOCATION_CONFIRMED: "ALLOCATION_CONFIRMED",
  ALLOCATION_WITHDRAWN: "ALLOCATION_WITHDRAWN",
  ROUND_OPENED: "ROUND_OPENED",
  ROUND_CLOSED: "ROUND_CLOSED",
  COURSE_CREATED: "COURSE_CREATED",
  COURSE_UPDATED: "COURSE_UPDATED",
  COURSE_CANCELLED: "COURSE_CANCELLED",
  COURSE_DELETED: "COURSE_DELETED",
  TIEBREAK_RESOLVED: "TIEBREAK_RESOLVED",
  POLICY_CHANGED: "POLICY_CHANGED",
  USER_CREATED: "USER_CREATED",
  OVERRIDE_APPLIED: "OVERRIDE_APPLIED",
  POINTS_REIMBURSED: "POINTS_REIMBURSED",
  IMPORT_COMPLETED: "IMPORT_COMPLETED",
  SOP_SCORED: "SOP_SCORED",
} as const;

export const NOTIFICATION_TYPE = {
  ROUND_OPENED: "ROUND_OPENED",
  ROUND_CLOSED: "ROUND_CLOSED",
  ALLOCATION_RESULT: "ALLOCATION_RESULT",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  COURSE_CANCELLED: "COURSE_CANCELLED",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  SYSTEM: "SYSTEM",
} as const;

export const DEFAULT_BID_POINTS = 1000;
export const MIN_BID_POINTS = 1;
export const MAX_COURSES_PER_STUDENT = 8;
export const MIN_CREDITS = 6;
export const MAX_CREDITS = 20;

// SOP configuration bounds (word-based)
export const SOP_WORD_LIMIT_MIN = 50;    // floor: at least 50 words required
export const SOP_WORD_LIMIT_MAX = 1000;  // ceiling: max 1000 words allowed
